### ISSUE TITLE
[BUG] PowerCLI Connect-VIServer fails with "Connect-VIServer: Value cannot be null. (Parameter 'source')"

### ISSUE THREAD

**Issue by et1975** [vmware/govmomi#2591]
PowerCLI `Connect-VIServer` fails with cryptic
> Connect-VIServer: Value cannot be null. (Parameter 'source')

**To Reproduce**
Given the docker-compose configuration:
```yaml
version: "3"
services:
  vcsim:
    image: nimmis/vcsim:latest
    ports:
      - 443:443
    restart: always
```

1. spin up the container 
1. use the powerCLI to try and connect to it
1. observe the error

**Expected behavior**
A successful login or a clear and concise error.

**Affected version**
nimmis/vcsim:latest

PowerCLI, Running on PowerShell Core 7.1 on Alpine:
```
(Get-Command Connect-VIServer).Module.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
12     4      0      18627056
```
