### ISSUE TITLE
Docker images based on alpine linux

### ISSUE THREAD

**Issue by fliiiix** [vmware/govmomi#2988]
**Is your feature request related to a problem? Please describe.**
I can not use the official docker image to run my gitlab ci job.

I have a gitlab job which looks like this:
```
.matrix_template: &matrix_template
  matrix:
    - IMAGE: ubuntu-bionic-cloudinit
      URL: https://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.ova
    - IMAGE: ubuntu-focal-cloudinit
      URL: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.ova

variables:
  GOVC_URL: XXX
  GOVC_USERNAME:XXX
  GOVC_PASSWORD: ${VSPHERE_PASSWORD}
  GOVC_DATACENTER: XXX
  GOVC_DATASTORE: XXX
  GOVC_CLUSTER: XXX
  GOVC_RESOURCE_POOL: XXX
  GOVC_NETWORK: XXX
  GOVC_FOLDER:XXX
  GOVC_INSECURE: 'true'

 get-images:
   stage: download
   image: galaad991/govc:0.24.0
   parallel:
     <<: *matrix_template
   script:
    - echo "Downloading public image [${IMAGE}-${TAG}]"
    - govc vm.destroy ${IMAGE}-${TAG} || true
    - govc import.ova -name ${IMAGE}-${TAG} -folder vm/${GOVC_FOLDER} ${URL}
    - govc vm.markastemplate ${IMAGE}-${TAG}
```

This wont work with the minimal official docker image, because `export` and things like `echo` are not supported.

**Describe the solution you'd like**
A image based on a minimal linux distro for example alpine would be great. 

**Describe alternatives you've considered**
The current way of providing environment is `-e` but I guess it is obvious from the example here that it does not scale.

Something like this:
```
script:
  - -e GOVC_URL=XXX -e GOVC_USERNAME=XXX -e GOVC_PASSWORD=${VSPHERE_PASSWORD} -e GOVC_DATACENTER=XXX -e GOVC_DATASTORE=XXX -e GOVC_CLUSTER=XXX -e GOVC_RESOURCE_POOL=XXX -e GOVC_NETWORK=XXX -e GOVC_FOLDER=XXX -e GOVC_INSECURE='true' vm.destroy ${IMAGE}-${TAG}
```
