### ISSUE TITLE
Unable to add portgroup

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#819]
While adding portgroup, I get following error message 

```
HostNetworkSystem:hostnetworksystem-85 does not implement: UpdateNetworkConfig
```

**Comment by anfernee** [comment]
@Akasurde can you clarify what command did you run, and what version of vcsim did you use? It will be very helpful for us to address the issue.

**Comment by Akasurde** [comment]
This is similar to other Ansible Playbook [error](https://github.com/vmware/govmomi/issues/822#issuecomment-333284963).

**Comment by Akasurde** [comment]
@anfernee All these requested features are required as these are part of Ansible VMware playbook testing effort. You can check more info about this [here](https://github.com/ansible/community/wiki/VMware%3A-testing-efforts).

**Comment by dougm** [comment]
@Akasurde the wiki page is just a list of govmomi github issues, does not provide any detail.  All we need are some steps to reproduce.

**Comment by Akasurde** [comment]
I am facing this issue while using vcsim with Ansible VMware module `vmware_vmkernel`.

`vmware_vmkernel.py` internally uses an API 

```
host_network_config_result = host_network_system.UpdateNetworkConfig(config, "modify")
```

I think this function is not implemented in vcsim, so Ansible module fails.

You can use following Ansible playbook to reproduce this error against latest govcsim code.

```yaml
---
- name: Port group
  hosts: localhost
  vars:
    - vcsim: 0.0.0.0
  tasks:
    - name: add vmkernel
      vmware_vmkernel:
        validate_certs: False
        hostname: "{{ vcsim }}"
        username: user
        password: pass
        vswitch_name: vswitch_0001
        portgroup_name: pg_0001
        vlan_id: 1
        ip_address: 192.168.10.1
        subnet_mask: 255.255.255.0
        enable_mgmt: True
      register: host_system_result_0001
```
