### ISSUE TITLE
Unable to perform vmkernel operation

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#822]
Adding new vmkernel raises following error 
  ```
  HostNetworkSystem:hostnetworksystem-85 does not implement: UpdateNetworkConfig
  ```

**Comment by anfernee** [comment]
@Akasurde can you clarify what command did you run, and what version of vcsim did you use? Thanks.

**Comment by Akasurde** [comment]
@anfernee Thanks for response. 

I am facing this issue while using vcsim with Ansible VMware module `vmware_vmkernel`.

`vmware_vmkernel` internally uses an API 

```
host_network_config_result = host_network_system.UpdateNetworkConfig(config, "modify")
```

I think this function is not implemented in vcsim, so Ansible module fails.

You can use following Ansible playbook to reproduce this error against latest govcsim code.

```yaml
---
- name: Port group
  hosts: localhost
  vars:
    - vcsim: 0.0.0.0
  tasks:
    - name: add host
      vmware_vmkernel:
        validate_certs: False
        hostname: "{{ vcsim }}"
        username: user
        password: pass
        vswitch_name: vswitch_0001
        portgroup_name: pg_0001
        vlan_id: 1
        ip_address: 192.168.10.1
        subnet_mask: 255.255.255.0
        enable_mgmt: True
      register: host_system_result_0001
```
