### ISSUE TITLE
vcsim does not check for guest os id

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#919]
vcsim does not validate [guest os id](https://www.vmware.com/support/developer/converter-sdk/conv43_apireference/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html) provided by automation 

I am using following Ansible playbook

```yaml

---
- name: Create a virtual machine
  hosts: localhost
  tasks:
    - name: create vm
      vmware_guest:
        datacenter: DC0
        esxi_hostname: DC0_H0
        hostname: 127.0.0.1
        name: DC0_H0_VM10
        folder: /vm
        validate_certs: False
        guest_id: sample
        username: user
        password: pass
        state: poweredon
        disk:
          - size_gb: 1
            type: thin
            datastore: LocalDS_0
        hardware:
            memory_mb: 512
            num_cpus: 1
            osid: centos64guest
            scsi: paravirtual
```

Run

```
$ ansible-playbook test_vmware_guest_os.yml
```

Here if guest_id is specified as 'sample', vcsim does not complain and creates VM.

Expected:
vcsim should complain about wrong guest id like ESXi server does.
