### ISSUE TITLE
Support 'numCoresPerSocket' in vcsim

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#929]
Currently, vcsim does not support 'numCoresPerSocket', so Could you please support this feature ?

Ansible Playbook

```yaml
---
- name: Create VM with 'numCoresPerSocket'
  hosts: localhost
  tasks:
    - name: create a vm
      vmware_guest:
        datacenter: DC0
        esxi_hostname: DC0_H0
        hostname: 127.0.0.1
        name: DC0_H0_VM4
        folder: /vm
        validate_certs: False
        guest_id: sample
        username: user
        password: pass
        state: poweredon
        disk:
          - size_gb: 1
            type: thin
            datastore: LocalDS_0
        hardware:
            memory_mb: 4096
            num_cpus: 4
            num_cpu_cores_per_socket: 2
            osid: centos64guest
            scsi: paravirtual
```

Actual PDB output : 
```
(Pdb) vmobj.config.hardware
(vim.vm.VirtualHardware) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   numCPU = 4,
   numCoresPerSocket = <unset>,
   memoryMB = 4096,
```

Expected PDB output : 

```
(Pdb) vmobj.config.hardware
(vim.vm.VirtualHardware) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   numCPU = 4,
   numCoresPerSocket = 2,
   memoryMB = 4096,
```
